name: 'Create Sub Issues'
description:
  "Create sub issues based on the task list in the parent issue's body"
author: 'Jawaad Khan'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
  trigger-label:
    description: 'The parent label to trigger the action'
    required: true

# Define your outputs here.
outputs:
  sub-issues:
    description: 'List of the sub issues created'

runs:
  using: node20
  main: dist/index.js
