name: 'Test sub tasks'
on:
  issues:
    types:
      - labeled
env:
  token: ${{ secrets.ACCESSTOKEN }}

jobs:
  create-sub-tasks:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.issue.labels.*.name, 'user story')  }}
    steps:
      - uses: './'
        with:
          github_token: ${{env.token}}
          trigger_label: 'user story'
